# Generated by Django 5.2.1 on 2025-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("daily_cost", models.FloatField()),
                ("periodic_cost", models.FloatField()),
                ("total_daily_consume", models.FloatField()),
                ("total_consume", models.FloatField()),
                ("periodic_consume", models.JSONField()),
                ("daily_cost_plot", models.TextField()),
                ("periodic_plot", models.TextField()),
                ("unitxgroup_plot", models.TextField()),
            ],
        ),
    ]
